### ISSUE TITLE
suggested

### ISSUE THREAD

**Issue by WarningDarbe** [ahihiyou20/discord-selfbot-owo-bot#1]
please add multi token and make open source code

**Comment by ahihiyou20** [comment]
> 

Obfuscate for security reasons tho. Multi token is not possible I guess... It is possible but a bit hard for me. Maybe later.

**Comment by leptryn** [comment]
pls let me know how to fix this issue 
![image](https://user-images.githubusercontent.com/104491645/165471939-2194f288-af86-43d8-a01d-0739ae8065e3.png)

**Comment by WarningDarbe** [comment]
If I'm not mistaken, it gives an error of a module that is not loaded, because the codes are hidden, it does not show which module it is.

**Comment by ahihiyou20** [comment]
> If I'm not mistaken, it gives an error of a module that is not loaded, because the codes are hidden, it does not show which module it is.

Yea mostly because some modules are not installed, this command should fix that error.
```
py -m pip install -r requirements.txt
```

**Comment by hung2705** [comment]
![image](https://user-images.githubusercontent.com/94538309/173736255-95da0313-e8c5-416e-861a-abd4003a7419.png)
pls help

**Comment by ahihiyou20** [comment]
> ![image](https://user-images.githubusercontent.com/94538309/173736255-95da0313-e8c5-416e-861a-abd4003a7419.png)
> pls help

Okay so somehow discum can’t fetch your Discord account username and other information like ID so the selfbot doesn’t work. Try it on others account
