### ISSUE TITLE
AttributeError: 'data' object has no attribute 'dmsID'

### ISSUE THREAD

**Issue by serjdan** [ahihiyou20/discord-selfbot-owo-bot#12]
Hi, I'm getting this error after I load data:
![image](https://user-images.githubusercontent.com/44371707/199817496-e59237e5-ad1a-41ed-8f6c-7e33e32b076f.png)

**Comment by ahihiyou20** [comment]
@serjdan Install the latest version on Github, which has the "discum" folder, and use main.py instead of Auto.exe

**Comment by serjdan** [comment]
Hey! thanks for your reply.
I had the latest version. The issue was I was using the .exe instead of main.py. Issue resolved! Thank you!
