### ISSUE TITLE
blackjack

### ISSUE THREAD

**Issue by GameWax** [ahihiyou20/discord-selfbot-owo-bot#2]
can you add blackjack support too? it's a great way to make more owo as well

**Comment by GameWax** [comment]
also, what do i put for `allowedid`, `webhookping` ?

**Comment by ahihiyou20** [comment]
> also, what do i put for `allowedid`, `webhookping` ?

Choose option 2 in the menu is a way to setup the selfbot. Change the settings through settings.json with Notepad is pretty good but it kinda confuse...
I would like to recommend you to use option 2 in the menu. Btw allowedid is the Discord account ID can use your Selfbot's command (if you enable it ). And  webhookping is the Discord user ID you want to ping through webhook if there is a captcha (if you enable it).

**Comment by ahihiyou20** [comment]
> also, neither can i run the source folder, coz it shows some json issues, and nor the main folder, since it shows: [7588] Cannot open PyInstaller archive from executable

Source folder having some settings.json issue and will be fix as soon as i can cuz im too lazy now. The [7588] error is because Pyinstaller having some unknown error.

**Comment by GameWax** [comment]
and last question, what is a secret token?

**Comment by ahihiyou20** [comment]
> and last question, what is a secret token?

So people keep selling my code. So i made a key system that require you to enter the correct key to use. You can get key for free in the discord server,channel: key.

**Comment by GameWax** [comment]
what is your server link?

**Comment by ahihiyou20** [comment]
> what is your server link?

Bruh in the README.md description
