### ISSUE TITLE
How to get dms channel id

### ISSUE THREAD

**Issue by ObsidianMC123** [ahihiyou20/discord-selfbot-owo-bot#2]
i look for on youtube but there don't have any video for this

**Comment by iamz4ri** [comment]
![image](https://user-images.githubusercontent.com/85773574/178093469-8c436d0a-5c49-457a-9517-ad656b866507.png)

**Comment by dwnnnnnnn** [comment]
> i look for on youtube but there don't have any video for this

![image](https://user-images.githubusercontent.com/85773574/178093479-08736357-ee92-4f6c-a6d3-7d1cea88fdf2.png)

**Comment by ahihiyou20** [comment]
> i look for on youtube but there don't have any video for this

![Screenshot_20220709-130440_Chrome](https://user-images.githubusercontent.com/95456402/178093919-954dba14-86a1-4d92-be16-214d69a71c1c.jpg)
