### ISSUE TITLE
KeyError: 'user'

### ISSUE THREAD

**Issue by GphantomR** [ahihiyou20/discord-selfbot-owo-bot#6]
![image_2022-08-22_194935808](https://user-images.githubusercontent.com/111744740/185914416-eeb38fd0-a550-4f33-954a-c494e923a3f0.png)

**Comment by NguyenHoaiBaxo** [comment]
same

**Comment by GphantomR** [comment]
nvm just found out its problem with my token, only works with few of my accounts, but not with some.

**Comment by ahihiyou20** [comment]
> 

Well that issue raised when your account is in a server has some channels, threads contain quotation marks. The solution is leave those server or delete those channel somehow.

**Comment by GphantomR** [comment]
> 

Yep, that fixed it. Thanks! :)

**Comment by invaliduser231** [comment]
> > 
> 
> Well that issue raised when your account is in a server has some channels, threads contain quotation marks. The solution is leave those server or delete those channel somehow.

I tried to leave all those servers ( if filtered them with an other selfbot ) but the error remains any other solution?

**Comment by ahihiyou20** [comment]
> > > 
> > 
> > 
> > Well that issue raised when your account is in a server has some channels, threads contain quotation marks. The solution is leave those server or delete those channel somehow.
> 
> I tried to leave all those servers ( if filtered them with an other selfbot ) but the error remains any other solution?

You can use an alt to run the Selfbot instead of your main. Or you can leave all servers and then join again to filter the server has that issue
