### ISSUE TITLE
Bot stopping working after a while

### ISSUE THREAD

**Issue by kanziletto** [ahihiyou20/discord-selfbot-owo-bot#7]
As title says bot stopping working when bot tryna send daily command.. Any idea? Thanks.
![image](https://user-images.githubusercontent.com/37486634/188707710-f345ceb0-df83-4c3b-aeee-058fc954b27d.png)

**Comment by ahihiyou20** [comment]
> As title says bot stopping working when bot tryna send daily command.. Any idea? Thanks. ![image](https://user-images.githubusercontent.com/37486634/188707710-f345ceb0-df83-4c3b-aeee-058fc954b27d.png)

I think it's because the Selfbot can't fetch the daily message, try run it in your personal server.

**Comment by kanziletto** [comment]
Okey seems fixed, thanks.
